### ISSUE TITLE
iOS Wallet and State Management Epic

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet-poc#8]
As a mobile wallet developer I would like an SDK that provides me with all of the tools necessary to observe blockchain state and my wallet reliably so that I can easily integrate zcash shielded support into my wallet.

Criteria:
- [ ] The SDK can download and decrypt blocks in order to find transactions that pertain to the wallet
- [ ] The SDK must be able to recognize, acknowledge, and rectify the effects of a blockchain reorganization
- [ ] Able to query for all transactions related to the wallet
- [ ] Able to query for the current wallet balance
- [ ] Able to query for the current block height
- [ ] Able to generate Sapling and transparent keys from ZIP32 seed
- [ ] Able to generate ZIP32 seed from BIP39 style mnemonic
- [ ] Able to generate addresses from their associated keys

**Comment by lindanlee** [comment]
test

**Comment by braddmiller** [comment]
Added this to the wrong repo. Moving and closing
